const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILIURE = "REGISTRATION_FAILIURE";

export { SET_ALERT, REMOVE_ALERT, REGISTRATION_SUCCESS, REGISTRATION_FAILIURE };
