const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILIURE = "REGISTRATION_FAILIURE";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT";
const USER_LOAD_FAILURE = "USER_LOAD_FAILURE";
const USER_LOADED = "USER_LOADED";
const GET_PROFILE = "GET_PROFILE";
const GET_PROFILES = "GET_PROFILES";
const PROFILE_ERROR = "PROFILE_ERROR";
const CLEAR_PROFILE = "CLEAR_PROFILE";
const CREATE_PROFILE = "CREATE_PROFILE";
const ADD_EXPERIENCE = "ADD_EXPERIENCE";
const ADD_EDUCATION = "ADD_EDUCATON";
const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
const DELETE_EDUCATION = "DELETE_EDUCATION";
const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export {
	SET_ALERT,
	REMOVE_ALERT,
	REGISTRATION_SUCCESS,
	REGISTRATION_FAILIURE,
	LOGIN_FAILURE,
	LOGIN_SUCCESS,
	LOGOUT,
	USER_LOADED,
	USER_LOAD_FAILURE,
	GET_PROFILE,
	PROFILE_ERROR,
	CLEAR_PROFILE,
	CREATE_PROFILE,
	ADD_EDUCATION,
	ADD_EXPERIENCE,
	DELETE_EDUCATION,
	DELETE_EXPERIENCE,
	GET_PROFILES,
	CLEAR_CURRENT_PROFILE,
};
