const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILIURE = "REGISTRATION_FAILIURE";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT";
const USER_LOAD_FAILURE = "USER_LOAD_FAILURE";
const USER_LOADED = "USER_LOADED";

export {
	SET_ALERT,
	REMOVE_ALERT,
	REGISTRATION_SUCCESS,
	REGISTRATION_FAILIURE,
	LOGIN_FAILURE,
	LOGIN_SUCCESS,
	LOGOUT,
	USER_LOADED,
	USER_LOAD_FAILURE,
};
